### ISSUE TITLE
Cannot add URL as Custom HACS repository

### ISSUE THREAD

**Issue by cbuxton5200** [Wetzel402/hass-cozi#1]
When trying to add https://github.com/Wetzel402/hass-cozi as a custom repository, I get an error that the repository structure for 2023.1.0. is not compliant.
![image](https://github.com/Wetzel402/hass-cozi/assets/59487049/fd6225db-5951-427c-9a74-eb014fbff851)

**Comment by Wetzel402** [comment]
I just removed and readded to my HACS instance with no issue.  HACS version 1.32.1.  Can I ask what version of HACS you are running? 

Edit: I noted in your screen shot that Lovelace is selected as the category.  Can you please try changing it to integration?
