### ISSUE TITLE
Feature request: Configuration ability to only sync specific lists

### ISSUE THREAD

**Issue by GSLaaitie** [Wetzel402/hass-cozi#3]
Hi.

Thanks for making this available.
My family uses Cozi extensively for planning, shopping, etc. So there is a ton of data in Cozi that I do not need in Home Assistant.
Would it be possible to only import my shopping list (AKA add a listid filter)?

Thanks in advance for your response/consideration

**Comment by Wetzel402** [comment]
I based the API calls off of reverse engineering the website and app.  When getting the lists there isn't a filter it just gets all the lists at the same time.  With that said, there might be a way to limit which lists are added as entities in HA but the data transferred in the background will be the same. 

Does that make sense?

**Comment by GSLaaitie** [comment]
It does. It doesn't make that big difference to me having all the list really. Thanks for taking the time to reply.

**Comment by Wetzel402** [comment]
I'm hoping to add support for the new todo entities in the future but life, school, and work tend to occupy my time... 

Thanks for using my integration.
